### ISSUE TITLE
For windows dll

### ISSUE THREAD

**Issue by polarbear88** [Taymindis/nginx-c-function#11]

**Comment by polarbear88** [comment]
Does it support linking dll under windows?

**Comment by Taymindis** [comment]
I don't think so, even managed to package, windows nginx has no multithreading support. I will suggest you create docker script on top on windows and the docker running linux OS.

After that install nginx, nginx-link-function and so on, and also you don't need to worry about your other windows server setup, just bring along the image for every windows servers.

[https://docs.docker.com/docker-for-windows/](docker-for-windows)
