### ISSUE TITLE
nginx: [emerg] unknown directive "ngx_http_c_func_link_lib" in /home/aimso/nginx-c-function/t/servroot/conf/nginx.conf

### ISSUE THREAD

**Issue by aimsomebody** [Taymindis/nginx-c-function#12]
t/sanity.t .. nginx: [emerg] unknown directive "ngx_http_c_func_link_lib" in /home/aimso/nginx-c-function/t/servroot/conf/nginx.conf:39
Bailout called.  Further testing stopped:  TEST 6: Set C_FUNC_TEST_GET_CALLOC_FROM_POOL - Cannot start nginx using command "nginx -p /home/aimso/nginx-c-function/t/servroot/ -c /home/aimso/nginx-c-function/t/servroot/conf/nginx.conf > /dev/null" (status code 256).
FAILED--Further testing stopped: TEST 6: Set C_FUNC_TEST_GET_CALLOC_FROM_POOL - Cannot start nginx using command "nginx -p /home/aimso/nginx-c-function/t/servroot/ -c /home/aimso/nginx-c-function/t/servroot/conf/nginx.conf > /dev/null" (status code 256).

**Comment by aimsomebody** [comment]
Hi, I tried to execute 'prove -r t/' to test nginx c function module but got error listed above.
Waiting for your further response.

**Comment by Taymindis** [comment]
have you compiled this module before running test? 
you should compile into your nginx first
```bash
./configure --add-module=/path/to/nginx-link-function
make -j2
sudo make install
```
and install the header file.
```bash
install -m 644 /path/to/nginx-link-function/src/ngx_link_func_module.h /usr/local/include/
```
Then run test

**Comment by aimsomebody** [comment]
It works. Thanks.
