### ISSUE TITLE
ngx_http_c_func_module.h not found in your system c header path, please copy latest ngx_http_c_func_module.h to your /usr/include or /usr/local/include

### ISSUE THREAD

**Issue by ahchinPeh** [Taymindis/nginx-c-function#4]
I have ady install ngx_http_c_func_module.h in /usr/local/include, why it keep prompting me this error

**Comment by Taymindis** [comment]
Are you cloning latest source code? I believe the header has updated, you just recopy the latest header file overwrite the old one will do

**Comment by ahchinPeh** [comment]
Great! it works now. Thanks
