### ISSUE TITLE
Logging?

### ISSUE THREAD

**Issue by david9100** [Taymindis/nginx-c-function#5]
Your example works great and I think that I'll be able to build off of that.  One question is that you give some logging examples:

`ngx_http_c_func_log(info, ctx, "%s", "Starting The Application");
`
but it does not seem to log anywhere.  Is there something special that must be done?

**Comment by minikawoon** [comment]
It is logging to your nginx error log path. Have you defined error log path
in your nginx?

**Comment by david9100** [comment]
That did the trick.  Thanks!
