### ISSUE TITLE
How to subrequest in async way by using `ngx_link_func_subrequest `

### ISSUE THREAD

**Issue by ahchinPeh** [Taymindis/nginx-c-function#8]

**Comment by Taymindis** [comment]
Please follow this link, it will guide you how to make sub-request without waiting for response

https://github.com/Taymindis/nginx-link-function/wiki/Tips-and-Tricks#10-ngx_link_func_subrequest-directive-for-you-multiple-subrequest-run-parallelasync-or-sequentialsync-using-ngx_link_func_add_header_inctx-or-ngx_link_func_add_req_header-directive-for-communicate-each-service-that-you-have-sub-requesting-to
